
[build]
  publish = "."

[[redirects]]
  # Avoid redirecting actual static files to index.html
  from = "/*.tsx"
  to = "/*.tsx"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/**/*.tsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/**/*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
