
[build]
  publish = "."

[[redirects]]
  # Ensure static assets are served directly
  from = "/index.tsx"
  to = "/index.tsx"
  status = 200

[[redirects]]
  # Handle SPA Routing
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/pages/*.tsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/services/*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/lib/*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
